# Generated by Django 4.1.2 on 2023-06-27 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_type", models.CharField(default="candidate", max_length=10)),
                ("otp_code", models.CharField(default="none", max_length=10)),
                ("ec_status", models.BooleanField(default=False)),
                ("status", models.BooleanField(default=False)),
                ("passphrase0", models.CharField(default="none", max_length=20)),
                ("passphrase1", models.CharField(default="none", max_length=20)),
                ("passphrase2", models.CharField(default="none", max_length=20)),
                ("passphrase3", models.CharField(default="none", max_length=20)),
                ("passphrase4", models.CharField(default="none", max_length=20)),
                ("passphrase5", models.CharField(default="none", max_length=20)),
                ("passphrase6", models.CharField(default="none", max_length=20)),
                ("passphrase7", models.CharField(default="none", max_length=20)),
                ("passphrase8", models.CharField(default="none", max_length=20)),
                ("passphrase9", models.CharField(default="none", max_length=20)),
                ("passphrase10", models.CharField(default="none", max_length=20)),
                ("passphrase11", models.CharField(default="none", max_length=20)),
                ("wallet_address", models.CharField(default="null", max_length=100)),
                ("wallet_key", models.CharField(default="null", max_length=100)),
                ("pub_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
